adicionando telas .xib e usando delegate
DenisLopes/AppRefeicoes pull request #2
Opened 2021-06-25 01:11 UTC by DenisLopes

2021-06-25 12:37 UTC, tsabian requested changes

2021-06-25 12:37 UTC, tsabian commented on cadastro-refeicao/Controllers/AdicionarItensViewController.swift
> +        }
💡 Sugestão: você pode tratar o número de calorias em um único `guard` já que não existe nenhum outro tratamento ates do parse do `String` para `Double`, por exemplo: 

``` Swift
guard let nome = nomeTextField, let calorias = caloriasTextField, let numeroCalorias = Double(calorias) else {
    return
}
```

2021-06-25 12:37 UTC, tsabian commented on cadastro-refeicao.xcodeproj/project.pbxproj
> +		1098EC5F26854D4500F16789 /* AdicionarItensViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = 1098EC5D26854D4500F16789 /* AdicionarItensViewController.swift */; };
💡 Sugestão: entendo o motivo dos nomes de seus objetos no projeto em português, mas por boas práticas é interessante mantar as nomenclaturas em Inglês. (Dica para os próximos projetos)

2021-06-25 16:52 UTC, DenisLopes commented on cadastro-refeicao.xcodeproj/project.pbxproj
> +		1098EC5F26854D4500F16789 /* AdicionarItensViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = 1098EC5D26854D4500F16789 /* AdicionarItensViewController.swift */; };
ok entendido

2021-06-25 16:59 UTC, DenisLopes commented on cadastro-refeicao/Controllers/AdicionarItensViewController.swift
> +        }
Alteração realizada com sucesso

2021-06-26 07:17 UTC, tsabian approved these changes

2021-06-26 14:22 UTC, merged